print('----and operator------')
print(1 > 0 and 4 < 5)
print(5 == 7 and 7 < 12)
print('----------------------')

print('----or operator-------')
print(12 == 12 or 15 < 7)
print(3 > 5 or 13 < 12)
print('----------------------')

print('----xor operator------')
print((4 == 4) ^ (3 > 4))
print(4 == 4)
print(3 > 4)
print('----------------------')

print('----not operator------')
print(not True)
print(not False)
print(not (2 > 1))
print('----------------------')

print('----equality operator------')
print(5 == 5)
print(10 == 5)
print('----------------------')